language: python
python:
- 2.7
- 3.3
install:
- pip install -e .
script: nosetests
notifications:
  slack:
    rooms:
      secure: HC1DduVinw33Icu1W+/Ugg2ZpL2W7DRI1TTTAUB86dOFYt78EKUrvf95nmvGwhsrQCoIp7z7KJbUlUBEo7+w18KrfY6XdQlZiy7aL/qhIJ+05BJ927tkkAZxx8GZE85Iv4JgIJ1wehPzWD1SJ1IUs3OnHm8yqZiqyDboCqzB2ls=
    on_success: change
    on_failure: always
