language: python
python:
- 2.7
- 3.3
install:
- pip install -e .
script: nosetests
notifications:
  slack:
    secure: Z2AHONgayOHQGnaKvkEL1LdLBbMh4WEdR3tlZwdor7GxrEFB1aoug7fpy115E4BwKr0mXeD2u9CfCRMinyZOBZu2rDqChCraQynOy5PYzmHjC8VI+saG7PyWfNTEeMr05c9zqSJomDcmlDEuhck5p00xLamuIFh3sQk7CLLrDh4=
